from app.schemas.puzzle import PuzzleResponse, PuzzleCreate
from app.schemas.move import MoveRequest, MoveResponse
from app.schemas.user import UserCreate, UserResponse, StreakResponse
from app.schemas.game import (
    GameCreate,
    GameJoin,
    GameResponse,
    GameMoveRequest,
    GameMoveResponse,
    PlayerInfo,
    GameMoveSchema,
    WSMessage,
    WSMoveMessage,
    WSGameOverMessage,
    WSPlayerJoinedMessage,
    WSGameStartMessage,
)
from app.schemas.bot_game import (
    BotGameCreate,
    BotGameResponse,
    BotMoveRequest,
    BotMoveResponse,
    BotGamePGN,
)
from app.schemas.lesson import (
    LessonResponse,
    LessonDetailResponse,
    LessonStepResponse,
    LessonProgressResponse,
    LessonWithProgressResponse,
    ValidateLessonMoveRequest,
    ValidateLessonMoveResponse,
    CategoryProgressResponse,
)
from app.schemas.achievement import (
    AchievementResponse,
    UserAchievementResponse,
    AchievementUnlockedResponse,
    UserAchievementsListResponse,
)

__all__ = [
    "PuzzleResponse",
    "PuzzleCreate",
    "MoveRequest",
    "MoveResponse",
    "UserCreate",
    "UserResponse",
    "StreakResponse",
    "GameCreate",
    "GameJoin",
    "GameResponse",
    "GameMoveRequest",
    "GameMoveResponse",
    "PlayerInfo",
    "GameMoveSchema",
    "WSMessage",
    "WSMoveMessage",
    "WSGameOverMessage",
    "WSPlayerJoinedMessage",
    "WSGameStartMessage",
    "BotGameCreate",
    "BotGameResponse",
    "BotMoveRequest",
    "BotMoveResponse",
    "BotGamePGN",
    "LessonResponse",
    "LessonDetailResponse",
    "LessonStepResponse",
    "LessonProgressResponse",
    "LessonWithProgressResponse",
    "ValidateLessonMoveRequest",
    "ValidateLessonMoveResponse",
    "CategoryProgressResponse",
    "AchievementResponse",
    "UserAchievementResponse",
    "AchievementUnlockedResponse",
    "UserAchievementsListResponse",
]
